#!/usr/bin/env bash

# Create the defeault .env file
cp ./.env.example ./.env

# Install composer dependencies
docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v $(pwd):/var/www/html \
    -w /var/www/html \
    laravelsail/php80-composer:latest \
    composer install --ignore-platform-reqs

# Copy a shortcut helper into the user's path to make it easier
# for the user to run commands
echo 'alias sandbox="~/teemill/laravel-sandbox/sandbox $@"' >> ~/.bashrc

# Reload the bash config with the new alias
source ~/.bashrc
